# SPDX-License-Identifier: GPL-2.0-or-later

# VIA protocol commands
CMD_VIA_GET_PROTOCOL_VERSION = 0x01
CMD_VIA_CUSTOM_GET_VALUE = 0x08

# Viable protocol (0xDF)
VIABLE_PREFIX = 0xDF
VIABLE_GET_PROTOCOL_INFO = 0x00
VIABLE_DEFINITION_SIZE = 0x0D
VIABLE_DEFINITION_CHUNK = 0x0E
VIABLE_DEFINITION_CHUNK_SIZE = 22
VIABLE_LAYER_STATE_GET = 0x16
VIABLE_LAYER_STATE_SET = 0x17
